# Generate k8s/secret.yaml from root .env (base64-encoded data fields)
# Usage: .\scripts\generate-k8s-secret.ps1

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$envFile = Join-Path $root ".env"
$outFile = Join-Path $root "k8s\secret.yaml"

if (-not (Test-Path $envFile)) {
    Write-Error ".env not found at $envFile"
}

function Get-EnvValue([string]$name) {
    $line = Get-Content $envFile | Where-Object { $_ -match "^\s*$name\s*=" } | Select-Object -First 1
    if (-not $line) { Write-Error "Missing $name in .env" }
    return ($line -split "=", 2)[1].Trim().Trim('"').Trim("'")
}

function To-B64([string]$value) {
    return [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($value))
}

$keys = @(
    "PINECONE_API_KEY",
    "GEMINI_API_KEY",
    "GOOGLE_CLIENT_ID",
    "GOOGLE_CLIENT_SECRET",
    "JWT_SECRET"
)

$dataLines = foreach ($key in $keys) {
    $val = Get-EnvValue $key
    "  ${key}: $(To-B64 $val)"
}

$yaml = @"
# AUTO-GENERATED by scripts/generate-k8s-secret.ps1 - do not commit (gitignored)
apiVersion: v1
kind: Secret
metadata:
  name: mediquery-secrets
  namespace: default
type: Opaque
data:
$($dataLines -join "`n")
"@

Set-Content -Path $outFile -Value $yaml -Encoding UTF8
Write-Host "Wrote $outFile (base64-encoded secrets from .env)"
